export class Texts {
    home() {
        return {
            LANDING_PAGE: {
                URL_HOME: "https://www.lumahealth.io/",
                URL_PARCIAL: "lumahealth.io",
                //   VEHICLE_INSURANCE: "Vehicle Insurance Application",
                //   THIS_IS_A_SAMPLE: "This is a sample application, Version 1.0.1",
                //   VISIT_SUPPORT_BUTTON: " Visit Support!",
                //   AUTOMOBILE_BUTTON: "Automobile",
                //   TRUCK_BUTTON: "Truck",
                //   MOTORCYCLE_BUTTON: "Motorcycle",
                //   CAMPER_BUTTON: "Camper",
                //   REQUEST_BUTTON: "Request Demo",
                //   HOME_BUTTON: "Home",
                //   UNDEFINED_INSURANCE_TEXT: "undefined Insurance",
                //   ENTER_VEHICLE: "Enter Vehicle Data12",
                //   ENTER_INSURANT: "Enter Insurant Data7",
                //   ENTER_PRODUCT: "Enter Product Data6",
                //   SELECT_PRICE: "Select Price Option1",
                //   SED_QUOTE: "Send Quote4",
                //   MAKE_OPTION: "BMW",
                //   MODEL_OPTION: "Motorcycle",
                //   CYLINDER_CAPACITY: "200",
                //   ENGINE_PERFORMANCE: "512",
                //   DATE: "10/26/2017",
                //   NUMBER_OF_SEATS_OPTION: "2",
                //   NUMBER_OF_SEATS_SECOND_OPTION: "2",
                //   FUEL_TIPE_OPTION: "Diesel",
                //   PLAYLOAD: "500",
                //   TOTAL_WEIGHT: "1500",
                //   LIST_PRICE: "20000",
                //   LICENSE_PLATE_NUMBER: "KGKH-10024",
                //   ANNUAL_MILEAHE: "30000",
                //   BUTTON_NEXT: "Next »",
                //   ABOUT_BUTTON: "About",
                //   PRODUCTS_BUTTON: "Products",
                //   EVENTS_BUTTON: "Events & Webinars",
                //   RESOURCES_BUTTON: "Resources",
                //   SERVICES_BUTTON: "Services",
                //   COPYRIHT: "Copyright 2021 by Tricentis GmbH. All rights reserved.",
            },
            TAB_TWO_TEXT: {
                //   FIRST_NAME: "Victor",
                //   LAST_NAME: "Fernandes",
                //   DATE_OF_BIRTH: "01/19/1992",
                //   STREET_ADDRESS: "200, Olivia Alves De Luna",
                //   COUNTRY: "Brazil",
                //   ZIPCODE: "58449000",
                //   CITY: "Campina Grande",
                //   LABEL_ZIPCODE: "Zip Code",
                //   LABEL_CITY: "City",
                //   LABEL_GENDER: "Gender",
                //   LABEL_WEBSITE: "Website",
                //   OCCUPATION: "Employee",
                //   WEBSITE: "google.com",
                //   BUTTON_NEXT_PRODUCT_DATA: "#nextenterproductdata",
            }
        };
    }
}
const texts = new Texts();
export default texts;