name: PR or Push to MAIN branch

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  continuous-integration: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Using Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.
        
    - name: Install dependencies
      run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev
      
    - name: run install, build and test
      run: |
          npm install
          npm run cypress:run -- --headless --browser chrome --config defaultCommandTimeout=60000
   
    - name: Upload Cypress results
      uses: actions/upload-artifact@v3
      with:
          name: cypress-results
          path: cypress/results
